gbolahanscrumy/urls.py
from django.urls import path
from . import views
from django.contrib.auth import urls
from django.urls import path, include
from django.contrib.auth.models import *
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from .views import *
app_name = 'gbolahanscrumy'
urlpatterns = [
path('', sign_up, name="signup"),
path('movegoal/<int:goal_id>', views.move_goal),
path('addgoal', views.add_goal),
path('home/', home, name='home'),
path('accounts/', include('django.contrib.auth.urls')),
path('accounts/signup/', sign_up, name='signup'),
path('addgoal/', add_goal, name='add'),
path('successpage/', TemplateView.as_view(
        template_name='gbolahanscrumy/successpage.html'), name='successpage'),
]

myfirstproject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('gbolahanscrumy/', include('gbolahanscrumy.urls')),


]

gbolahanscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, CharField, PasswordInput, Form
# Create your models here.

class GoalStatus(models.Model):
        status_name = models.CharField(max_length=200)
        
        def __str__(self):
                return self.status_name


class ScrumyGoals(models.Model):
    goal_name= models.CharField(max_length=50)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length=100)
    moved_by = models.CharField(max_length=100)
    owner = models.CharField(max_length=100)
    goal_status = models.ForeignKey(GoalStatus,null=True, on_delete = models.PROTECT)
    user = models.ForeignKey(User, related_name='goals',null=True,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.goal_name

class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length=100)
    created_by = models.CharField(max_length=100)
    moved_from = models.CharField(max_length=100)
    moved_to = models.CharField(max_length=100)
    time_of_action = models.DateTimeField('Time of Action')
    goal = models.ForeignKey(ScrumyGoals, on_delete =models.PROTECT)

    def __str__(self):
        return self.created_by

class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user']

gbolahanscrumy/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
 
 
class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password\n (Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.)', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
 
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
 
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email
 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
 
        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
 
        return password2
 
    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

gbolahanscrumy/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.db import models
from django.contrib.auth.models import User
from gbolahanscrumy.models import *
from django.http import HttpResponse
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.contrib.auth.models import Group
from django.contrib.auth.forms import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib import messages
import random

def index1(request):
    return HttpResponse("This is a Scrum Application")

# def index(request, *args, **kwargs):    
  #  qs = ScrumyGoals.objects.filter(goal_name="Learn Django").get()
   #  return HttpResponse(f'{qs}')

def home(request):
    users = User.objects.all()

    def get_by_status(status_name):
        goals = GoalStatus.objects.get(status_name=status_name)
        status_goals = goals.scrumygoals_set.all()
        return status_goals

    daily_goals = get_by_status("Daily Goal")
    weekly_goals = get_by_status("Weekly Goal")
    verify_goals = get_by_status("Verify Goal")
    done_goals = get_by_status("Done Goal")

    dictionary = {
        'users': users,
        'weekly_goals': weekly_goals,
        'daily_goals': daily_goals,
        'verify_goals': verify_goals,
        'done_goals': done_goals,
    }
    return render(request, 'gbolahanscrumy/home.html', dictionary)
def move_goal(request, goal_id):
    try:
        obj = ScrumyGoals.objects.get(goal_id=goal_id)
    except Exception as e:
        return render(request, 'exception.html',
        {'error':'A record with that goal id does not exist'})
    else:
        return HttpResponse(obj.goal_name)

@login_required(login_url="/gbolahanscrumy/accounts/login")

def sign_up(request):
    f = CustomUserCreationForm(request.POST)
    if f.is_valid():
        f.save()
        messages.success(request, 'Account created successfully')
        response = redirect('successpage/')
        return response
    else:
        f = CustomUserCreationForm()
 
    return render(request, 'registration/signup.html', {'form': f})

def add_goal(request):
    form = CreateGoalForm
    if request.method == 'POST':
        form = form(request.POST)
        data = request.POST.dict()
        user = User.objects.get(id=data['user'])
        add_goal = form.save(commit=False)
        add_goal.goal_id = random.randint(1000,9990)
        add_goal.created_by = user.username
        add_goal.moved_by = user.username
        add_goal.owner = user.username
        status = GoalStatus.objects.get(status_name="Daily Goal")
        add_goal.goal_status = status
        add_goal.save()
        return HttpResponseRedirect('/gbolahanscrumy/home' )
    context = {'create_goal': form }
    
    return render(request, 'gbolahanscrumy/addgoal.html', context)

gbolahanscrumy/templates/exception.html
<p> {{error}}
</p>

gbolahanscrumy/templates/gbolahanscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">

	<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Goal Page</title>
	</head>

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: sans-serif;
    }

    .container {
        width: 980px;
        height: 400px;
        margin: 50px auto;
        text-align: center;
        background-color: orange;
    }

    body {
        background-color: lightblue;
    }

    form {
        padding-top: 2rem;
    }

    input[type=submit] {
        padding: 10px;
        border: none;
        border-radius: 10px;
        background-color: blue;
        color: #fff;
        cursor: pointer;
    }

    input {
        padding: 10px;
        border-radius: 5px;
    }
</style>

	<body>


		<div class="container">
    <form method='POST'>
        {% csrf_token %}
        {{create_goal}}
  		<input type="submit">
    </form>
		</div>
	</body>
</html>

gbolahanscrumy/templates/gbolahanscrumy/exception.html
<p> {{error}}
</p>

gbolahanscrumy/templates/gbolahanscrumy/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }

        .container {
            width: 980px;
            height: 400px;
            margin: 50px auto;
            text-align: center;
            background-color: orange;
        }

        body {
            background-color: lightblue;
        }


        table,
        th,
        td {
            border: 1px solid black;
        }

        table {
            width: 100%;
        }

        th {
            height: 50px;
            text-align: center;
        }

        .table-container {
            width: 600px;
            margin: 0 auto;
            padding-top: 50px;
            margin-top: 50px;
        }

        .btn-down {
            margin-top: 20px;

        }
   .btn-down a {
            text-decoration: none;
            background-color: blue;
            padding: 10px;
            border-radius: 20px;
            color: #fff;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="table-container">
            <table>
                <tr>
                    <th>User</th>
                    <th>Weekly Goals</th>
                    <th>Daily Goals</th>
                    <th>Verify Goals</th>
                    <th>Done Goals</th>
                </tr>
                {% for user in users %}
                <tr>
                    <td>{{user}}</td>
                    <td>{% for goal in weekly_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in daily_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in verify_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in done_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>



                    {% endfor %}
                </tr>

            </table>
  </div>

        <p class="btn-down"> <a href={% url 'gbolahanscrumy:add' %}>ADD A GOAL</a></p>
    </div>

</body>

</html>

gbolahanscrumy/templates/gbolahanscrumy/successpage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Success Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }

        .container {
            width: 980px;
            height: 400px;
            margin: 50px auto;
            text-align: center;
            background-color: orange;
        }

        body {
            background-color: lightblue;
        }

        p {
            margin-top: 20px;
            padding-top: 100px;
            font-size: 30px;
            margin-bottom: 50px;

        }

        .btn-down {
            text-decoration: none;
            background-color: blue;
            padding: 10px;
            border-radius: 20px;
            color: #fff;

        }
    </style>

</head>

<body>
    <div class="container">
        <p>Your Account has been created successfully, <br> Login with your username and password</p>
        <a class="btn-down" href={% url 'gbolahanscrumy:login'%}>Login to your account</a>
    </div>


</body>

gbolahanscrumy/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }

        .container {
            width: 980px;
            height: 400px;
            margin: 50px auto;
            text-align: center;
            background-color: orange;
        }

        body {
            background-color: lightblue;
        }


        table,
        th,
        td {
            border: 1px solid black;
        }

        table {
            width: 100%;
        }

        th {
            height: 50px;
            text-align: center;
        }

        .table-container {
            width: 600px;
            margin: 0 auto;
            padding-top: 50px;
            margin-top: 50px;
        }

        .btn-down {
            margin-top: 20px;

        }
   .btn-down a {
            text-decoration: none;
            background-color: blue;
            padding: 10px;
            border-radius: 20px;
            color: #fff;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="table-container">
            <table>
                <tr>
                    <th>User</th>
                    <th>Weekly Goals</th>
                    <th>Daily Goals</th>
                    <th>Verify Goals</th>
                    <th>Done Goals</th>
                </tr>
                {% for user in users %}
                <tr>
                    <td>{{user}}</td>
                    <td>{% for goal in weekly_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in daily_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in verify_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in done_goals%}
                        {%if goal.user.username == user.username%}
                        {{goal}}
                        {%endif%}
                        {%endfor%}
                    </td>



                    {% endfor %}
                </tr>

            </table>
  </div>

        <p class="btn-down"> <a href={% url 'gbolahanscrumy:add' %}>ADD A GOAL</a></p>
    </div>

</body>

</html>